version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          NODEJS_VERSION: 20
    volumes:
      - ../:/home/node/app
      #- /home/node/app/node_modules
    ports:
      - 3300:3000