version: '3.9'

services:
  dbserver:
    image: mongo:7
    volumes:
      - mondodb_data:/data/db/
      - /etc/timezone:/etc/timezone:ro
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      #MONGO_INITDB_DATABASE: init
    ports:
      - "27017:27017"


  mongoexpress:
    image: mongo-express
    depends_on:
      - dbserver
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@dbserver:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - 8900:8081


volumes:
  mondodb_data