version: '3.9'

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/html/
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
      #- /var/www/html/vendor
      #- /var/www/html/node_modules
    ports:
      - 8000:80