version: "3.8"

services:
    webserver:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                APACHE_PUBLIC_PATH: /var/www/html${PROJECT_PATH}${PROJECT_PATH_PUBLIC}
                PHP_APACHE_VERSION: ${PHP_APACHE_VERSION}
                XDEBUG_VERSION: ${XDEBUG_VERSION}
                NODEJS_VERSION: ${NODEJS_VERSION}
        volumes:
            - ../:/var/www/html${PROJECT_PATH}
            - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
            #- /var/www/html${PROJECT_PATH}/vendor
            #- /var/www/html${PROJECT_PATH}/node_modules
        ports:
            - ${HOST_PORT}:80
        environment:
            - CHOKIDAR_USEPOLLING=true
